---
type: pipeline
name: Build Enable Actual

when:
  workerGroup:
    include: [soldier]
  trigger:
    include: [commit, action]
  file:
    include:
      - package.json
      - .reeve.yaml
  action:
    include: [enable-actual:build]

steps:
  - name: Get package version
    task: '@reeve/node-get-package-version'

  - name: Get Actual version
    task: node:alpine
    command: sh
    input: |
      set -e
      cd /reeve/src
      apk update && apk add jq curl
      npm install --production
      ACTUAL_VERSION=`npm list '@actual-app/api' --depth=0 --json | jq -er '.dependencies["@actual-app/api"].version'`
      curl -fso /dev/null -w "Status %{http_code}\n" "$REEVE_API/api/v1/var?key=ACTUAL_VERSION&value=${ACTUAL_VERSION}"

  - name: Build image
    task: '@docker/build'
    params:
      DOCKER_LOGIN_REGISTRIES: { env: docker/hub/2manyvcos/login }
      NAME: docker.io/2manyvcos/enable-actual
      TAG: { var: PACKAGE_VERSION }
      TAG_ALIASES: >
        latest
        actual${ACTUAL_VERSION}
        ${TAG}-actual${ACTUAL_VERSION}
      PLATFORM: amd64,arm64
      BUILD_DRIVER: docker-container
      ACTUAL_VERSION: { var: ACTUAL_VERSION }
