---
type: trigger
cron: 0 0 * * *
action: ':images:docker.io/2manyvcos/enable-actual:build-latest'

---
type: pipeline
name: build image - docker.io/2manyvcos/enable-actual

when:
  workerGroup:
    include: [soldier]
  trigger:
    include: [commit, action]
  file:
    include:
      - package.json
      - .reeve.yaml
  action:
    include:
      - images:docker.io/2manyvcos/enable-actual:build
      - ':images:docker.io/2manyvcos/enable-actual:build-latest'

steps:
  - name: get package version
    task: '@reeve/node-get-package-version'

  - name: install dependencies
    task: node:alpine
    command: sh
    input: |
      set -e
      cd /reeve/src
      npm install --production

  - name: update actual client
    when:
      trigger:
        include: [action]
      action:
        include: [':images:docker.io/2manyvcos/enable-actual:build-latest']
    task: node:alpine
    command: sh
    input: |
      set -e
      cd /reeve/src
      npm install @actual-app/api@latest

  - name: get actual version
    task: node:alpine
    params:
      PACKAGE_VERSION: { var: PACKAGE_VERSION }
    command: sh
    input: |
      set -e
      cd /reeve/src
      apk add --no-cache jq curl
      ACTUAL_VERSION=`npm list '@actual-app/api' --depth=0 --json | jq -er '.dependencies["@actual-app/api"].version'`
      curl -fso /dev/null -w "Status %{http_code}\n" "$REEVE_API/api/v1/var?key=ACTUAL_VERSION&value=${ACTUAL_VERSION}"
      curl -fso /dev/null -w "Status %{http_code}\n" "$REEVE_API/api/v1/var?key=LONG_TAG&value=${PACKAGE_VERSION}-actual${ACTUAL_VERSION}"

  - name: build image - docker.io/2manyvcos/enable-actual
    task: '@docker/build'
    params:
      DOCKER_LOGIN_REGISTRIES: { env: docker/hub/2manyvcos/login }
      NAME: docker.io/2manyvcos/enable-actual
      TAG: { var: LONG_TAG }
      TAG_ALIASES: >
        latest
        ${PACKAGE_VERSION}
        actual${ACTUAL_VERSION}
      PLATFORM: amd64,arm64
      BUILD_DRIVER: docker-container
      PACKAGE_VERSION: { var: PACKAGE_VERSION }
      ACTUAL_VERSION: { var: ACTUAL_VERSION }
